name: Smoke test for FW Build

run-name: ${{ github.actor }} has made changes to code

on:
  push:
    branches:
      - 'main'
      - 'release/**'
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'

jobs:
  smoke:
    runs-on: ubuntu-latest

    container:
      image: brinth/esp8266_rtos_sdk:main
      options: --rm
      volumes:
        - ${{ github.workspace }}:/project

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Creating secret.h
        working-directory: /project
        run: |
          cat << EOF >> secret.h
          #ifndef __SECRET_H__
          #define __SECRET_H__
          #define CONFIG_WIFI_SSID "Fool"
          #define CONFIG_WIFI_PASS "ing you"
          #endif
          EOF
          make && echo "Build Success" || echo "Build Broken"
